group_config:
  # Labels are based on https://keepachangelog.com/en/1.0.0/#types
  # Update them to match your own labels.

  # Added for new features.
  - title: Added
    labels:
      - added

  # Changed for changes in existing functionality.
  - title: Changed
    labels:
      - changed

  # Deprecated for soon-to-be removed features.
  - title: Deprecated
    labels:
      - deprecated

  # Removed for now removed features.
  - title: Removed
    labels:
      - removed

  # Fixed for any bug fixes.
  - title: Fixed
    labels:
      - fixed

  # Security in case of vulnerabilities.
  - title: Security
    labels:
      - security
