name: Changelog PR

on:
  push:
    branches:
      # Run this action when the following branch is pushed to.
      # Keep this in sync with with.branch below.
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Run Changelog PR
        uses: JonathanAquino/changelog-pr@HEAD   # Normally please put a version here like @v0.9.0
        with:
          changelog_filename: CHANGELOG.md
          config_file: changelog-pr-config.yaml
          # Commit the changelog to this branch.
          # Keep this in sync with on.push.branches above.
          branch: master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
